=== JBearded/CronScheduler/src/main/resources/scheduler.dtd
<!ELEMENT scheduler (quartz-config,tasks)>
<!ELEMENT quartz-config (property*)>
<!ELEMENT property EMPTY>
<!ATTLIST property
        key CDATA #REQUIRED
        value CDATA #REQUIRED>
<!ELEMENT tasks (task*)>
<!ELEMENT task (method*)>
<!ATTLIST task
        id CDATA #REQUIRED
        class CDATA #REQUIRED>
<!ELEMENT method (param*)>
<!ATTLIST method
        name CDATA #REQUIRED
        cronExpression CDATA #REQUIRED>
<!ELEMENT param EMPTY>
<!ATTLIST param
        value CDATA #REQUIRED
        type (byte|short|int|long|boolean|float|double|char|string) string>

=== JBearded/CronScheduler/src/test/resources/scheduler.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scheduler SYSTEM "scheduler.dtd">
<scheduler>
    <quartz-config>
        <property key="org.quartz.scheduler.instanceName" value="DefaultQuartzScheduler"></property>
        <property key="org.quartz.scheduler.rmi.export" value="false"></property>
        <property key="org.quartz.scheduler.rmi.proxy" value="false"></property>
        <property key="org.quartz.scheduler.wrapJobExecutionInUserTransaction" value="false"></property>
        <property key="org.quartz.threadPool.threadCount" value="20"></property>
        <property key="org.quartz.threadPool.threadPriority" value="5"></property>
        <property key="org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread" value="true"></property>
        <property key="org.quartz.jobStore.misfireThreshold" value="60000"></property>
    </quartz-config>
    <tasks>
        <task id="service" class="Service">
            <method name="put"  cronExpression="0/30 * * * * ?">
                <param value="1" type="string"></param>
                <param value="ha" type="string"></param>
            </method>
        </task>
    </tasks>
</scheduler>
